# Generated by Django 4.2.6 on 2023-10-19 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('costo', models.PositiveIntegerField()),
                ('horario', models.CharField(max_length=20)),
                ('cupo', models.PositiveIntegerField()),
                ('cat_image', models.ImageField(blank=True, upload_to='photos/cursos')),
                ('descripcion', models.TextField(blank=True)),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profesores.profesor')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
    ]
