# Generated by Django 4.2.6 on 2023-10-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_curso_creat_date_curso_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='nombre',
            new_name='curso_name',
        ),
        migrations.AddField(
            model_name='curso',
            name='category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='curso',
            name='slug',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
