# Generated by Django 4.2.6 on 2023-10-19 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_rename_curso_name_curso_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='nombre',
            new_name='curso_name',
        ),
    ]
