# Generated by Django 4.2.6 on 2023-10-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_rename_nombre_curso_curso_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='curso_name',
            new_name='nombre',
        ),
    ]
