# Generated by Django 4.2.6 on 2023-10-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_rename_curso_name_curso_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='cat_image',
            field=models.ImageField(upload_to='photos/cursos'),
        ),
    ]
