# Generated by Django 4.2.6 on 2023-10-20 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('cursos', '0008_alter_curso_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.categorias'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='category',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
