# Generated by Django 4.2.6 on 2023-10-20 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_curso_categoria_alter_curso_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='categoria',
        ),
    ]
