# Generated by Django 4.2.6 on 2023-10-20 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('cursos', '0012_remove_curso_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.categorias'),
        ),
    ]
