# Generated by Django 4.2.6 on 2023-11-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_catedratico'),
    ]

    operations = [
        migrations.AddField(
            model_name='catedratico',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
