# Generated by Django 4.2.6 on 2023-11-22 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_accounts_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catedratico',
            old_name='contraseña',
            new_name='password',
        ),
    ]
