# Generated by Django 4.2.6 on 2023-11-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_contraseña_catedratico_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='catedratico',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
