# Generated by Django 4.2.6 on 2023-11-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_catedratico_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catedratico',
            name='password',
        ),
        migrations.AlterField(
            model_name='catedratico',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
