# Generated by Django 4.2.6 on 2023-11-22 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_catedratico_last_login_catedratico_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catedratico',
            name='username',
        ),
    ]
