# Generated by Django 4.2.6 on 2023-11-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_catedratico_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='catedratico',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
