# Generated by Django 4.2.6 on 2023-11-23 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0013_alter_curso_category'),
        ('accounts', '0012_catedratico_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='catedratico',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.curso'),
        ),
    ]
