# Generated by Django 4.2.6 on 2023-11-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_catedratico_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_account',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='catedratico',
            name='is_catedratico',
            field=models.BooleanField(default=True),
        ),
    ]
