# Generated by Django 4.2.6 on 2023-11-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_account_is_account_catedratico_is_catedratico'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_catedratico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catedratico',
            name='is_account',
            field=models.BooleanField(default=False),
        ),
    ]
