# Generated by Django 4.2.6 on 2023-11-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_account_is_catedratico_catedratico_is_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
