# Generated by Django 4.2.6 on 2023-10-21 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_rename_slug_categorias_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorias',
            old_name='category_slug',
            new_name='slug',
        ),
    ]
