# Generated by Django 4.2.6 on 2023-10-21 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_rename_category_slug_categorias_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorias',
            old_name='slug',
            new_name='category_slug',
        ),
    ]
