# Generated by Django 4.2.6 on 2023-10-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='dpi',
            field=models.IntegerField(help_text='Enter a positive integer.', unique=True),
        ),
    ]
