# Generated by Django 4.2.6 on 2023-10-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0002_alter_profesor_dpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='category',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
