# Generated by Django 4.2.6 on 2023-10-20 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('profesores', '0005_alter_profesor_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='Categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.categorias'),
        ),
    ]
