# Generated by Django 4.2.6 on 2023-10-20 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0006_profesor_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='Categoria',
        ),
    ]
